--SQL tafla fyrir vemblu, refagagnagrunninn
--Gagnatöflur

CREATE TABLE GRENI (
	Id   			CHAR(7) PRIMARY KEY,
	Nafn			VARCHAR(50),
	Stadsetning		POINT,
	SveitarfelagID	CHAR(7),
	Lysing			TEXT
);

CREATE TABLE AGN (
	Id		        CHAR(7) PRIMARY KEY,
	Stadsetning		POINT,
	SveitarfelagID	CHAR(7),
	Dagsetning		DATE,
	Lysing			TEXT,
	Skothus			BOOLEAN,
	Ljos			BOOLEAN
);

CREATE TABLE NOTENDUR (
	Kennitala		CHAR(10) PRIMARY KEY,
	Nafn			VARCHAR(50),
	Heimilisfang	VARCHAR(50),
	Póstnúmer		CHAR(3),
	SveitarfelagID	CHAR(7) REFERENCES SVEITARFELOG,
	Simi			CHAR(7),
	Tölvupóstur		VARCHAR(50)
);

CREATE TABLE VEIDIMENN (	
	Kennitala 		CHAR(10) PRIMARY KEY,
	Veidikortanumer CHAR(6),
	Skotvopnaleyfi	CHAR(14),
	FOREIGN KEY (Kennitala) REFERENCES NOTENDUR
);

CREATE TABLE VISINDAMENN (
	Kennitala 		CHAR(10) PRIMARY KEY,
	StofnunID 		CHAR(7) NOT NULL,
	FOREIGN KEY (Kennitala) REFERENCES NOTENDUR
);

CREATE TABLE GRENJASKYTTUR (
	Kennitala 		CHAR(10) NOT NULL,	
	SveitarfelagID	CHAR(7) NOT NULL,
	PRIMARY KEY (Kennitala, SveitarfelagID),
	FOREIGN KEY (Kennitala) REFERENCES VEIDIMENN,
	FOREIGN KEY (SveitarfelagID) REFERENCES SVEITARFELOG
);

CREATE TABLE REFIR (
	RefurID 		CHAR(7) PRIMARY KEY,
	Aldur			INTEGER,
	Kyn				CHAR(7),
	Thyngd			INTEGER,
	Lysing			TEXT
);

CREATE TABLE SJUKDOMAR (
	SjukdomurID		CHAR(7) PRIMARY KEY,
	Nafn			VARCHAR(50) UNIQUE NOT NULL,
	Lysing			TEXT
);

CREATE TABLE LITIR (
	LiturID			CHAR(7) PRIMARY KEY,
	Nafn			VARCHAR(50) UNIQUE NOT NULL,
	Lysing			TEXT
);

CREATE TABLE SVEITARFELOG (
	SveitarfelagID	CHAR(7) PRIMARY KEY,
	Nafn			VARCHAR(50) UNIQUE NOT NULL,
	Kennitala		CHAR(10),
	Heimilisfang	VARCHAR(50),
	Postnumer		CHAR(3),
	Simi			CHAR(7),
	Netfang			VARCHAR(50),
	Heimasida		VARCHAR(50)
);
--Tengitoflur

CREATE TABLE SYKTIRREFIR (
	RefurID			CHAR(7) NOT NULL,
	SjukdomurID		CHAR(7) NOT NULL,
	Lysing			TEXT,
	PRIMARY KEY (RefurID, SjukdomurID),
	FOREIGN KEY (RefurID) REFERENCES REFIR,
	FOREIGN KEY (SjukdomurID) REFERENCES SJUKDOMAR
);

CREATE TABLE VITJADGRENIS (
	Id				CHAR(7) PRIMARY KEY,
	GreniID			CHAR(7) NOT NULL,
	Kennitala		CHAR(10),
	Dagsetning		DATE NOT NULL,
	Virkt			BOOLEAN,
	Lysing			TEXT,
	FOREIGN KEY (GreniID) REFERENCES GRENI (GreniID)
);

CREATE TABLE AGRENI (
	Id				CHAR(7) PRIMARY KEY,
	GreniID			CHAR(7) NOT NULL,
	Dagsetning		DATE NOT NULL,
	TimiFra			TIME NOT NULL,
	TimiTil			TIME
);

CREATE TABLE SKYTTURAGRENI (
	Kennitala		CHAR(10) NOT NULL,
	AGreniID		CHAR(7) NOT NULL,
	PRIMARY KEY (Kennitala, AGreniID),
	FOREIGN KEY (Kennitala) REFERENCES GRENJASKYTTUR,
	FOREIGN KEY (AGreniID) REFERENCES AGreni (Id)
);

CREATE TABLE AAGNI (
	Id				CHAR(7) PRIMARY KEY,
	AgnID			CHAR(7) NOT NULL,
	Dagsetning		DATE NOT NULL,
	TimiFra			TIME NOT NULL,
	TimiTil			TIME
);

CREATE TABLE SKYTTURAAGNI (
	Kennitala		CHAR(10) NOT NULL,
	AAgniID			CHAR(7) NOT NULL,
	PRIMARY KEY (Kennitala, AAgniID),
	FOREIGN KEY (Kennitala) REFERENCES VEIDIMENN,
	FOREIGN KEY (AAgniID) REFERENCES AAGNI (Id)
);

CREATE TABLE REFURSAST (
	Id				CHAR(7) NOT NULL,
	Kennitala		CHAR(10),
	Stadsetning		POINT,
	Dagsetning		DATE,
	Timi			TIME
);

-------------------------
